### ISSUE TITLE
Introduce EnumDescriptor as a way of describing EnumValueTypes

### ISSUE THREAD

**Issue by evomimic** [evomimic/map-descriptors2#41]
Enums are an important data structure that needs to be supported in the MAP proof-of-concept. This story extends ValueDescriptorDetails to include an `Enum` variant and its associated `EnumDescriptor`. 

See the [MAP Property Descriptors wiki](https://github.com/evomimic/map-descriptors2/wiki/MAP-Property-Descriptors) for details of Enum descriptors.

### Task:

- [x] Introduce Enum as a variant in BaseType, ValueType, and ValueDescriptorDetails enums
- [ ] Enhance test fixtures to test enum functionality
- [ ] All sweetests pass
